routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/* User Interface */

Route::get('/', 'FrontController@index')->name('welcome');
Route::get('suratkelahiran', 'FrontController@surat_kelahiran')->name('suratkelahiran');
Route::get('suratkematian', 'FrontController@surat_kematian')->name('suratkematian');
Route::get('suratpindah', 'FrontController@surat_pindah')->name('suratpindah');
Route::get('suratpenghantarnikah', 'FrontController@surat_nikah')->name('suratnikah');
Route::get('suratizinusaha', 'FrontController@surat_izin_usaha')->name('suratizinusaha');

/* Request Surat Online */
Route::resource('reqsuratonline', 'User\RequestSuratKelahiranController');
Route::resource('reqsuratonlinedead', 'User\RequestSuratKematianController');
Route::resource('reqsuratonlinepindah', 'User\RequestSuratPindahController');
Route::resource('reqsuratonlinenikah', 'User\RequestSuratNikahController');
Route::resource('reqsuratonlineusaha', 'User\RequestSuratUsahaController');
/* End User Interface */

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/dashboardUser', 'HomeController@index')->name('user');

Route::group(['middleware' => ['auth' => 'CekRole:admin,karyawan,lurah'], 'prefix' => 'Superadmin'], function () {
    Route::namespace('Superadmin')->group(function () {
        Route::resource('kelurahan', 'kelurahanController');
        Route::resource('dusun', 'DusunController');
        Route::resource('kk', 'KKController');
        Route::get('add/{id}', 'KKController@add')->name('add');
        Route::post('addstore', 'KKController@add_store')->name('addstore');
        Route::resource('penduduk', 'PendudukController');
        Route::resource('kelahiran', 'KelahiranController');
        Route::resource('kematian', 'KematianController');
        Route::resource('pendatang', 'PendatangController');
        Route::resource('pindah', 'PindahController');
        Route::resource('staff', 'StaffController');
        Route::get('laporan', 'LaporanController@viewLaporan')->name('viewLaporan');
        Route::get('laporan/print/periodik', 'LaporanController@index')->name('LaporanPeriodik');
        Route::get('laporan/print/kematian', 'LaporanController@printKematian')->name('LaporanKematian');
        Route::get('laporan/print/pindah', 'LaporanController@printPindah')->name('LaporanPindah');
        Route::get('laporan/print/pendatang', 'LaporanController@printPendatang')->name('LaporanPendatang');
        Route::get('laporan/print/ketUsaha', 'LaporanController@printKetUsaha')->name('LaporanKetUsaha');
        Route::get('laporan/print/nikah', 'LaporanController@printNikah')->name('LaporanNikah');
        Route::resource('suratusaha', 'SuratusahaController');
        Route::resource('suratnikah', 'SuratnikahController');
        Route::resource('suratonline', 'ReqSuratOnlineController');
        Route::get('suratnikah/{id}/print', 'SuratnikahController@print')->name('suratnikah.print');
        Route::get('suratusaha/{id}/print', 'SuratusahaController@print')->name('suratusaha.print');
        Route::get('pindah/{id}/print', 'PindahController@print')->name('pindah.print');
        Route::get('kematian/{id}/print', 'KematianController@print')->name('kematian.print');
        Route::post('autofill', 'KematianController@autofill')->name('autofill');
        Route::post('autofillsuratusaha', 'SuratusahaController@autofillsuratusaha')->name('autofillsuratusaha');
        Route::post('autofillsuratnikah', 'SuratnikahController@autofillsuratnikah')->name('autofillsuratnikah');
        Route::post('autofillsuratpindah', 'PindahController@autofill')->name('autofillsuratpindah');
        Route::post('autofillsuratpendatang', 'PendatangController@autofill')->name('autofillsuratpendatang');

        // Autofill From Request
        Route::post('autofillfromreq', 'KematianController@autofillfromrequest')->name('autofillfromrequest');
        Route::post('autofillfromreqpindah', 'PindahController@autofillfromrequest')->name('autofillfromrequestpindah');
        Route::post('autofillfromreqnikah', 'SuratnikahController@autofillfromrequest')->name('autofillfromrequestnikah');
        Route::post('autofillfromrequsaha', 'SuratusahaController@autofillfromrequest')->name('autofillfromrequestusaha');

        /* Content Frontend */
        Route::resource('slider', 'SliderController');
        Route::resource('profile', 'ProfileController');
        /* End Content Frontend */
    });
});

app/Staff.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Staff extends Model
{
    protected $table = 'staffs';
    protected $fillable = [
        'kelurahan_id',
        'dusun_id',
        'nik',
        'nip',
        'nama',
        'jenis_kelamin',
        'tempat_lahir',
        'tanggal_lahir',
        'jabatan',
        'alamat',
        'no_hp',
        'email',
    ];

    public function kelurahan()
    {
        return $this->belongsTo(Kelurahan::class);
    }

    public function dusun()
    {
        return $this->belongsTo(Dusun::class);
    }
}

app/Http/Controllers/Superadmin/DusunController.php
<?php

namespace App\Http\Controllers\Superadmin;

use App\Http\Controllers\Controller;
use App\Dusun;
use App\Kelurahan;
use Illuminate\Http\Request;

class DusunController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Dusun::paginate(10);
        $kelurahan = Kelurahan::first();
        return view('Superadmin.dusun.index', compact('data', 'kelurahan'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'kelurahan_id' => 'required',
            'nama_dusun' => 'required',
        ]);

        $data = $request->all();
        Dusun::create($data);

        toast('Data Dusun berhasil ditambahkan', 'success')->position('bottom-end');
        return redirect()->route('dusun.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Dusun::findOrFail($id);
        $kelurahan = Kelurahan::first();
        return view('Superadmin.dusun.edit', compact('data', 'kelurahan'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'kelurahan_id' => 'required',
            'nama_dusun' => 'required',
        ]);

        $data = $request->all();
        Dusun::findOrFail($id)->update($data);

        toast('Data Dusun berhasil diubah', 'success')->position('bottom-end');
        return redirect()->route('dusun.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Dusun::findOrFail($id)->delete();

        toast('Data Dusun telah dihapus', 'error')->position('bottom-end');
        return redirect()->route('dusun.index');
    }
}

app/Http/Controllers/Superadmin/KKController.php
<?php

namespace App\Http\Controllers\Superadmin;

use App\Http\Controllers\Controller;
use App\KK;
use App\Kelurahan;
use App\Dusun;
use App\Penduduk;
use Illuminate\Http\Request;

class KKController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = KK::paginate(10);
        return view('Superadmin.kk.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $kelurahan = Kelurahan::first();
        $dusun = Dusun::all();
        return view('Superadmin.kk.create', compact('kelurahan', 'dusun'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'kelurahan_id' => 'required',
            'dusun_id' => 'required',
            'no_kk' => 'required',
            'alamat' => 'required',
            'nama_kepalakeluarga' => 'required',
        ]);

        $data = $request->all();
        $kk = new KK;
        $kk->kelurahan_id = $data['kelurahan_id'];
        $kk->dusun_id = $data['dusun_id'];
        $kk->no_kk = $data['no_kk'];
        $kk->nama_kepalakeluarga = $data['nama_kepalakeluarga'];
        $kk->alamat = $data['alamat'];
        $kk->save();

        foreach ($data['nik'] as $item => $value) {
            $data2 = array(
                'kelurahan_id' => $data['kelurahan_id'],
                'dusun_id' => $data['dusun_id'],
                'kk_id' => $kk->id,
                'nik' => $data['nik'][$item],
                'nama' => $data['nama'][$item],
                'tempat_lahir' => $data['tempat_lahir'][$item],
                'tanggal_lahir' => $data['tanggal_lahir'][$item],
                'jenis_kelamin' => $data['jenis_kelamin'][$item],
                'agama' => $data['agama'][$item],
                'pendidikan' => $data['pendidikan'][$item],
                'pekerjaan' => $data['pekerjaan'][$item],
                'status_perkawinan' => $data['status_perkawinan'][$item],
                'golongan_darah' => $data['golongan_darah'][$item],
                'hubungan_keluarga' => $data['hubungan_keluarga'][$item],
                'kewarganegaraan' => $data['kewarganegaraan'][$item],
                'rt' => $data['rt'][$item],
                'rw' => $data['rw'][$item],
                'nama_ayah' => $data['nama_ayah'][$item],
                'nama_ibu' => $data['nama_ibu'][$item],
                'status_kependudukan' => 'Aktif'
            );
            // dd($data2);
            Penduduk::create($data2);
        }

        toast('Data Kartu Keluarga berhasil ditambahkan', 'success')->position('bottom-end');
        return redirect()->route('kk.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = KK::with('penduduk')->findOrFail($id);
        // dd($data);
        return view('Superadmin.kk.show', compact('data'));
    }

    public function add($id)
    {
        $data = KK::with('penduduk')->findOrFail($id);
        // dd($data);
        return view('Superadmin.kk.tambah', compact('data'));
    }

    public function add_store(Request $request)
    {
        $data = $request->all();
        // dd($data);
        foreach ($data['nik'] as $item => $value) {
            $data2 = array(
                'kelurahan_id' => $data['kelurahan_id'],
                'dusun_id' => $data['dusun_id'],
                'kk_id' => $data['kk_id'],
                'nik' => $data['nik'][$item],
                'nama' => $data['nama'][$item],
                'tempat_lahir' => $data['tempat_lahir'][$item],
                'tanggal_lahir' => $data['tanggal_lahir'][$item],
                'alamat' => $data['alamat'][$item],
                'jenis_kelamin' => $data['jenis_kelamin'][$item],
                'agama' => $data['agama'][$item],
                'pendidikan' => $data['pendidikan'][$item],
                'pekerjaan' => $data['pekerjaan'][$item],
                'status_perkawinan' => $data['status_perkawinan'][$item],
                'golongan_darah' => $data['golongan_darah'][$item],
                'hubungan_keluarga' => $data['hubungan_keluarga'][$item],
                'kewarganegaraan' => $data['kewarganegaraan'][$item],
                'rt' => $data['rt'][$item],
                'rw' => $data['rw'][$item],
                'nama_ayah' => $data['nama_ayah'][$item],
                'nama_ibu' => $data['nama_ibu'][$item],
                'status_kependudukan' => 'Aktif'
            );
            // dd($data2);
            Penduduk::create($data2);
        }

        toast('Anggota Keluarga berhasil ditambahkan', 'success')->position('bottom-end');
        return redirect()->route('kk.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = KK::findOrFail($id);
        $kelurahan = Kelurahan::first();
        $dusun = Dusun::all();
        return view('Superadmin.kk.edit', compact('data', 'kelurahan', 'dusun'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'kelurahan_id' => 'required',
            'dusun_id' => 'required',
            'no_kk' => 'required',
            'nama_kepalakeluarga' => 'required',
        ]);

        $data = $request->all();
        KK::findOrFail($id)->update($data);

        toast('Data Kartu Keluarga berhasil diubah', 'success')->position('bottom-end');
        return redirect()->route('kk.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        KK::findOrFail($id)->delete();

        toast('Data Kartu Keluarga berhasil dihapus', 'error')->position('bottom-end');
        return redirect()->route('kk.index');
    }
}

app/Http/Controllers/Superadmin/KelurahanController.php
<?php

namespace App\Http\Controllers\Superadmin;

use App\Http\Controllers\Controller;
use App\Kelurahan;
use Illuminate\Http\Request;

class KelurahanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Kelurahan::paginate(10);
        return view('Superadmin.kelurahan.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nama_kelurahan' => 'required',
        ]);

        $data = $request->all();
        Kelurahan::create($data);

        toast('Data Kelurahan berhasil ditambahkan', 'success')->position('bottom-end');
        return redirect()->route('kelurahan.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Kelurahan::findOrFail($id);
        return view('Superadmin.kelurahan.edit', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'nama_kelurahan' => 'required',
        ]);

        $data = $request->all();
        Kelurahan::findOrFail($id)->update($data);

        toast('Data Kelurahan berhasil diubah', 'success')->position('bottom-end');
        return redirect()->route('kelurahan.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Kelurahan::findOrFail($id)->delete();

        toast('Data Kelurahan telah dihapus', 'error')->position('bottom-end');
        return redirect()->route('kelurahan.index');
    }
}

resources/views/Superadmin/staff/index.blade.php
@extends('layouts.front.backend')

@section('content')
    <div class="container-fluid py-4">
        <nav aria-label="breadcrumb" style="margin-bottom: 10px">
            <ol class="breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5">
                <li class="breadcrumb-item text-sm"><a class="opacity-5 text-dark" href="{{ route('home') }}">Dashboard</a>
                </li>
                <li class="breadcrumb-item text-sm text-dark active" aria-current="page"></li>
            </ol>
            <h6 class="font-weight-bolder mb-0">Data Staff</h6>
        </nav>

        <a class="btn bg-gradient-info w-25 mt-4 mb-3" href="{{ route('staff.create') }}"><i
                class="fas fa-plus"></i>&nbsp;
            Tambah Data Staff</a>

        <div class="row">
            <div class="col-12">
                <div class="card mb-4">
                    <div class="card-header pb-0"></div>
                    <div class="card-body px-0 pt-0 pb-2">
                        <div class="table-responsive p-0">
                            <table class="table align-items-center mb-0">
                                <thead>
                                    <tr>
                                        <th
                                            class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">
                                            NIK</th>
                                        <th
                                            class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">
                                            NIP</th>
                                        <th
                                            class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">
                                            Nama</th>
                                        <th
                                            class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">
                                            Tempat, Tanggal Lahir</th>
                                        <th
                                            class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">
                                            Umur</th>
                                        <th class="text-secondary opacity-7"></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @forelse ($data as $item)
                                        <tr>
                                            <td>
                                                <div class="d-flex px-2 py-1">
                                                    <div class="d-flex flex-column justify-content-center">
                                                        <h6 class="mb-0 text-sm">{{ $item->nik }}</h6>
                                                    </div>
                                                </div>
                                            </td>
                                            <td>
                                                <div class="d-flex px-2 py-1">
                                                    <div class="d-flex flex-column justify-content-center">
                                                        <h6 class="mb-0 text-sm">{{ $item->nip }}</h6>
                                                    </div>
                                                </div>
                                            </td>
                                            <td>
                                                <div class="d-flex px-2 py-1">
                                                    <div class="d-flex flex-column justify-content-center">
                                                        <h6 class="mb-0 text-sm">{{ $item->nama }}</h6>
                                                    </div>
                                                </div>
                                            </td>
                                            <td>
                                                <div class="d-flex px-2 py-1">
                                                    <div class="d-flex flex-column justify-content-center">
                                                        <h6 class="mb-0 text-sm">{{ $item->tempat_lahir }},
                                                            {{ date('d/m/Y', strtotime($item->tanggal_lahir)) }}
                                                        </h6>
                                                    </div>
                                                </div>
                                            </td>
                                            <td>
                                                <div class="d-flex px-2 py-1">
                                                    <div class="d-flex flex-column justify-content-center">
                                                        <h6 class="mb-0 text-sm">
                                                            @php
                                                                $tgl_lahir = new DateTime($item->tanggal_lahir);
                                                                $today = new DateTime();
                                                                $umur = $today->diff($tgl_lahir);
                                                            @endphp
                                                            {{ $umur->y }} tahun
                                                        </h6>
                                                    </div>
                                                </div>
                                            </td>
                                            <td>
                                                <div class="btn-group">
                                                    <button type="button" class="btn btn-info dropdown-toggle"
                                                        data-bs-toggle="dropdown" aria-expanded="false">
                                                        Action
                                                    </button>
                                                    <ul class="dropdown-menu">
                                                        <li><a href="{{ route('staff.edit', $item->id) }}"
                                                                class="dropdown-item"><i class="fas fa-edit"></i>
                                                                Edit</a>
                                                        </li>
                                                        <li><a href="{{ route('staff.show', $item->id) }}"
                                                                class="dropdown-item"><i class="fas fa-eye"></i>
                                                                Detail</a>
                                                        </li>
                                                        <form action="{{ route('staff.destroy', $item->id) }}"
                                                            method="POST"
                                                            onsubmit="return confirm('Hapus Data, Anda Yakin ?')">
                                                            {!! method_field('delete') . csrf_field() !!}
                                                            <li><button class="dropdown-item" type="submit">
                                                                    <i class="fas fa-trash"></i> Delete
                                                                </button></li>
                                                        </form>
                                                    </ul>
                                                </div>
                                            </td>
                                        </tr>
                                    @empty
                                        <tr>
                                            <td colspan="5" class="text-center">
                                                <h6 class="text-secondary"><i>Data Masih Kosong!</i></h6>
                                            </td>
                                    @endforelse
                                </tbody>
                            </table>
                        </div>
                        <div class="text-center">
                            {{ $data->links() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection